config/routes.rb
Rails.application.routes.draw do
  #                 USERS ROUTES

  get 'users/index'
  devise_for :users, controllers: {  sessions: 'users/sessions'  }
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  resources :users, :only =>[:show]
  get 'users/:id', to: 'users#show', as: 'show_user'
 
  # Friends routes

  match '/users',   to: 'users#index',   via: 'get'
  post 'users/send_friend_request/:id', to: 'users#send_friend_request', as: 'send_friend_request'
  delete 'users/remove_friend_request/:id', to: 'users#remove_friend_request', as: 'remove_friend_request'
  delete 'users/remove_friend/:id', to: 'users#remove_friend', as: 'remove_friend'
  post 'users/block_friend/:id', to: 'users#block_friend', as: 'block_friend'
  delete 'users/un_block_friend/:id', to: 'users#un_block_friend', as: 'un_block_friend'
  post 'users/accept_friend_request/:id', to: 'users#accept_friend_request', as: 'accept_friend_request'

  # Profile
  scope 'users' do
    post '/friends/:profile_id', to: 'users#friends', as: 'friends'
    post '/groups/:profile_id', to: 'users#groups', as: 'user_groups'
    get 'privacy/:id', to: 'users#edit_privacy', as: 'edit_privacy'
    patch 'privacy/:id', to: 'users#update_privacy', as: 'profile_privacy'
  end

  # Events routes

  resources :events do  
    post 'going', to: 'events#save_going', as: 'going'
    post 'interested', to: 'events#save_interested', as: 'interested'
    delete 'delete_invitation', to: 'events#delete_invitation', as: 'delete_invitation'
    delete 'delete_response', to: 'events#delete_response', as: 'delete_response'
  end

  get "comments/index"
  resources :posts do
    resources :comments
  end
  # Post Reactions routes
  #Like
  post "posts/:id/likes", to: "likes#create", as: "add_likes"
  delete "posts/:id/likes/:id", to: "likes#destroy", as: "remove_likes"
  #Angry
  post "posts/:id/angry", to: "angries#create", as: "add_angry"
  delete "posts/:id/angry/:id", to: "angries#destroy", as: "remove_angry"
  #Heart
  resources :hearts, only: [:create, :destroy]
  post "posts/:id/hearts", to: "hearts#create", as: "add_hearts"
  delete "posts/:id/hearts/:id", to: "hearts#destroy", as: "remove_hearts"
  #Sad
  post "posts/:id/sads", to: "sads#create", as: "add_sads"
  delete "posts/:id/sads/:id", to: "sads#destroy", as: "remove_sads"
  #Wow
  post "posts/:id/wows", to: "wows#create", as: "add_wows"
  delete "posts/:id/wows/:id", to: "wows#destroy", as: "remove_wows"
  # Comment Delete and Update Routes
  delete "posts/:id/comment/:id", to: "comments#destroy_comment", as: "destroy_comment"
  put "posts/:id/comments/:id", to: "comments#update_comment", as: "update_comment"


  #                    GROUPS ROUTES
  

  get 'groups', to: 'groups#index' ,as: 'groups'
  post 'groups/index', to: 'groups#create',as: 'groups_create'
  get 'groups/new', to: 'groups#new'
  post 'groups/join_group/:id', to: 'groups#join_group' , as: 'join_group'
  delete 'groups/remove_user_from_group/:id', to: 'groups#remove_user_from_group' , as: 'remove_user_from_group'
  delete 'groups/delete/:id', to: 'groups#delete' , as: 'delete'

  # Notifications

  get 'notifications/:user_id', to: 'notifications#index', as:'show_notifications'

  # Not found
  get 'not_found', to: 'pages#not_found', as:'not_found'

  root to: "home#index", as:"home"

  # locale
  get '*path?locale=:locale', to: 'application#switch_locale', as: 'switch'

  # will cause storage photos not to render
  #get "*path", to: redirect('not_found')
  

end

app/models/group.rb
class Group < ApplicationRecord
    has_many :user_groups
    has_many :users, through: :user_groups
    validates :name , length: { minimum: 1 , message: "Group name cannot be empty" }
end

app/models/user.rb
class User < ApplicationRecord
  after_save :profile_privacy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_picture
  # Friendlist Association
  has_many :friendlists
  has_many :friends, through: :friendlists
  has_many :friend_requests_sent, ->{where(status: false)}, class_name: 'Friendlist'
  has_many :requests_sent, through: :friend_requests_sent, source: :friend
  has_many :friend_requests_received, ->{where(status: false)}, class_name: 'Friendlist', foreign_key: 'friend_id'
  has_many :requests_received, through: :friend_requests_received, source: :user
  # Blocklist Association
  has_many :block_lists
  has_many :blocked_friend, through: :block_lists

  
  has_and_belongs_to_many :invited_to_events, class_name: 'Event'

  has_many :events, dependent: :destroy

  has_many :event_interests, dependent: :destroy
  has_many :interested_to_events, through: :event_interests, source: :event

  has_many :event_going_users, dependent: :destroy
  has_many :going_to_events, through: :event_going_users, source: :event
  # Validations 


  validates :profile_picture, blob: { content_type: :image }
  #user group
  has_many :user_groups
  has_many :groups, through: :user_groups
  # Post Associations
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes
  has_many :angries
  has_many :hearts
  has_many :sads
  has_many :wows
  after_commit :add_default_avatar, on: %i[create update]

  # Notification
  has_many :notifications, dependent: :destroy

  # Profile Privacy
  has_one :privacy, dependent: :destroy, class_name: 'ProfilePrivacy'

  #validates :profile_privacy, presence: true
  
  # Validations 

  after_commit :add_default_avatar
  validates_presence_of :user_name
  validates :user_name, length: { minimum: 2 , message: "cannot be less than 3 characters" }
  validates_format_of :user_name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/ , message: "is invalid"
  validates_uniqueness_of :phone_number
  validates :phone_number,:presence => true,
                 :numericality => true,
                 :length => { :minimum => 10, :maximum => 15 }


                 
  private
  def add_default_avatar
    unless profile_picture.attached?
      profile_picture.attach(
        io: File.open(
          Rails.root.join(
            'app','assets','images','avatar.png'
          )
        ),
        filename: 'avatar.png',
        content_type: 'image/png'
      )
    end
  end

  def profile_privacy
    
    user = User.last
    user.privacy = ProfilePrivacy.create
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create,:join_group]
  before_action :correct_user?, only: [:destroy]

  def create
    @newGroup = Group.new
    @newGroup.name = params[:name]
    @newGroup.created_by_id = current_user.id
    @newGroup.save
    current_user.groups << @newGroup
    message = "#{current_user.user_name} created group #{@newGroup.name}"
    scope = current_user.friends
    SendNotificationsJob.perform_now({:message => message, :scope => scope})
  end

  def join_group
    current_user.groups << Group.find(params[:id])
  end

  def remove_user_from_group
    p params
    current_user.user_groups.find_by_group_id(params[:id]).delete
  end
 

  def destroy
    Group.find(params[:id]).delete
  end

  def index
    @groups = Group.all
  end
  
  def update

  end

  def new

  end


  def correct_user?
    group = Group.find_by(id: params[:id])
    redirect_to new_user_session_url, notice: "Please sign in " unless group.created_by_id == current_user
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group.html.erb
<div class="card-header bg-white border-bottom-0">
            <div class="row">
                  <div class="card">
                        <p>
                              <strong><%= group.name %></strong>
                        </p>
                        <p>
                        <%flagGroup = true%>
                        <% current_user.group_ids.each do |check|%>
                              <%if check == group.id%>
                                    <%flagGroup = false%>
                              <%end%>
                        <%end%>
                        <%if flagGroup%>
                              <%= button_to 'Join' ,join_group_path(group.id) %>
                        <%else%>
                              Joined
                        <%end%>
                        </p>
                        <p>
                        <strong>Members</strong><br>      
                        <% group.users.each do |member|%>
                              <%= image_tag member.profile_picture,class:"rounded-circle",style:"max-width:4%"%>
                              <strong><a href="<%= user_url(member)%>"><%=member.user_name%></a></strong><br>
                        <%end%>
                        </p>
                        <p>
                        <%if current_user.id == group.created_by_id%>
                              <%= button_to 'Delete' , delete_path(group.id) , method: :delete%>
                        <%end%>
                        </p>
                  </div>
            </div>
      </div>

app/views/groups/index.html.erb
<h1><%= t"Groups" %> </h1>

<%@groups.each do |group|%>
      <%= render group %>
<%end%>

<%= form_tag("/groups/index", method: "post") do %>
    <%= label_tag :name %><br>
    <%= text_field_tag :name %>
    <br>
    
    <p>
    <%= submit_tag t("Add new group") %>
    </p>
<% end %>