config/routes.rb
Rails.application.routes.draw do
  #                 USERS ROUTES

  get 'users/index'
  devise_for :users, controllers: {  sessions: 'users/sessions'  }
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  resources :users, :only =>[:show]
  get 'users/:id', to: 'users#show', as: 'show_user'
 
  # Friends routes

  match '/users',   to: 'users#index',   via: 'get'
  post 'users/send_friend_request/:id', to: 'users#send_friend_request', as: 'send_friend_request'
  delete 'users/remove_friend_request/:id', to: 'users#remove_friend_request', as: 'remove_friend_request'
  delete 'users/remove_friend/:id', to: 'users#remove_friend', as: 'remove_friend'
  post 'users/block_friend/:id', to: 'users#block_friend', as: 'block_friend'
  delete 'users/un_block_friend/:id', to: 'users#un_block_friend', as: 'un_block_friend'
  post 'users/accept_friend_request/:id', to: 'users#accept_friend_request', as: 'accept_friend_request'

  # Profile
  scope 'users' do
    post '/friends/:profile_id', to: 'users#friends', as: 'friends'
    post '/groups/:profile_id', to: 'users#groups', as: 'user_groups'
    get 'privacy/:id', to: 'users#edit_privacy', as: 'edit_privacy'
    patch 'privacy/:id', to: 'users#update_privacy', as: 'profile_privacy'
  end

  # Events routes

  resources :events do  
    post 'going', to: 'events#save_going', as: 'going'
    post 'interested', to: 'events#save_interested', as: 'interested'
    delete 'delete_invitation', to: 'events#delete_invitation', as: 'delete_invitation'
    delete 'delete_response', to: 'events#delete_response', as: 'delete_response'
  end

  get "comments/index"
  resources :posts do
    resources :comments
  end
  # Post Reactions routes
  #Like
  post "posts/:id/likes", to: "likes#create", as: "add_likes"
  delete "posts/:id/likes/:id", to: "likes#destroy", as: "remove_likes"
  #Angry
  post "posts/:id/angry", to: "angries#create", as: "add_angry"
  delete "posts/:id/angry/:id", to: "angries#destroy", as: "remove_angry"
  #Heart
  resources :hearts, only: [:create, :destroy]
  post "posts/:id/hearts", to: "hearts#create", as: "add_hearts"
  delete "posts/:id/hearts/:id", to: "hearts#destroy", as: "remove_hearts"
  #Sad
  post "posts/:id/sads", to: "sads#create", as: "add_sads"
  delete "posts/:id/sads/:id", to: "sads#destroy", as: "remove_sads"
  #Wow
  post "posts/:id/wows", to: "wows#create", as: "add_wows"
  delete "posts/:id/wows/:id", to: "wows#destroy", as: "remove_wows"
  # Comment Delete and Update Routes
  delete "posts/:id/comment/:id", to: "comments#destroy_comment", as: "destroy_comment"
  put "posts/:id/comments/:id", to: "comments#update_comment", as: "update_comment"


  #                    GROUPS ROUTES
  

  get 'groups', to: 'groups#index' ,as: 'groups'
  post 'groups/index', to: 'groups#create',as: 'groups_create'
  get 'groups/new', to: 'groups#new'
  post 'groups/join_group/:id', to: 'groups#join_group' , as: 'join_group'
  delete 'groups/remove_user_from_group/:id', to: 'groups#remove_user_from_group' , as: 'remove_user_from_group'
  delete 'groups/delete/:id', to: 'groups#delete' , as: 'delete'

  # Notifications

  get 'notifications/:user_id', to: 'notifications#index', as:'show_notifications'

  # Not found
  get 'not_found', to: 'pages#not_found', as:'not_found'

  root to: "home#index", as:"home"

  # locale
  get '*path?locale=:locale', to: 'application#switch_locale', as: 'switch'

  # will cause storage photos not to render
  #get "*path", to: redirect('not_found')
  

end

app/models/user.rb
class User < ApplicationRecord
  after_save :profile_privacy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_picture
  # Friendlist Association
  has_many :friendlists
  has_many :friends, through: :friendlists
  has_many :friend_requests_sent, ->{where(status: false)}, class_name: 'Friendlist'
  has_many :requests_sent, through: :friend_requests_sent, source: :friend
  has_many :friend_requests_received, ->{where(status: false)}, class_name: 'Friendlist', foreign_key: 'friend_id'
  has_many :requests_received, through: :friend_requests_received, source: :user
  # Blocklist Association
  has_many :block_lists
  has_many :blocked_friend, through: :block_lists

  
  has_and_belongs_to_many :invited_to_events, class_name: 'Event'

  has_many :events, dependent: :destroy

  has_many :event_interests, dependent: :destroy
  has_many :interested_to_events, through: :event_interests, source: :event

  has_many :event_going_users, dependent: :destroy
  has_many :going_to_events, through: :event_going_users, source: :event
  # Validations 


  validates :profile_picture, blob: { content_type: :image }
  #user group
  has_many :user_groups
  has_many :groups, through: :user_groups
  # Post Associations
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes
  has_many :angries
  has_many :hearts
  has_many :sads
  has_many :wows
  after_commit :add_default_avatar, on: %i[create update]

  # Notification
  has_many :notifications, dependent: :destroy

  # Profile Privacy
  has_one :privacy, dependent: :destroy, class_name: 'ProfilePrivacy'

  #validates :profile_privacy, presence: true
  
  # Validations 

  after_commit :add_default_avatar
  validates_presence_of :user_name
  validates :user_name, length: { minimum: 2 , message: "cannot be less than 3 characters" }
  validates_format_of :user_name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/ , message: "is invalid"
  validates_uniqueness_of :phone_number
  validates :phone_number,:presence => true,
                 :numericality => true,
                 :length => { :minimum => 10, :maximum => 15 }


                 
  private
  def add_default_avatar
    unless profile_picture.attached?
      profile_picture.attach(
        io: File.open(
          Rails.root.join(
            'app','assets','images','avatar.png'
          )
        ),
        filename: 'avatar.png',
        content_type: 'image/png'
      )
    end
  end

  def profile_privacy
    
    user = User.last
    user.privacy = ProfilePrivacy.create
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_privacy
  
  def index
    @users=[]
    users = User.all
    users.each{
      |user|
      unless user == current_user
        unless user.friends.where(id: current_user.id).count > 0 or current_user.friends.where(id: user.id).count > 0
          unless user.blocked_friend.where(id: current_user.id).count > 0 or current_user.blocked_friend.where(id: user.id).count > 0
            @users.append(user)
          end
        end
      end
    }
  end

  def show
    @user = User.find_by_id(params[:id])
    if @user == nil
      redirect_to not_found_path
      return
    end 
    @groups = @user.user_groups
  end

  def friends
    @user = User.find_by_id(params[:profile_id])
  end

  def groups
    @user = User.find_by_id(params[:profile_id])
  end

  def send_friend_request
    if user_signed_in?
      @newfriend = Friendlist.new
      @newfriend.user_id = current_user.id
      @temp = User.find(params[:id])
      @newfriend.friend_id = @temp.id
      @newfriend.save
      redirect_to users_index_url
    else
      redirect_to new_user_session_url
    end
  end

  def accept_friend_request
    @accept = Friendlist.find_by_friend_id(params[:id])
    @accept.update_attribute(:status, true)
    @invertfriend = Friendlist.new
    @invertfriend.user_id = current_user.id
    @temp = User.find(params[:id])
    @invertfriend.friend_id = @accept.user_id
    @invertfriend.status = true
    @invertfriend.save
  end

  def remove_friend_request
    Friendlist.find_by_friend_id(params[:id]).delete
    redirect_to user_url(current_user)
  end

  def remove_friend
    @deleteFirst = Friendlist.find_by_user_id(params[:id])
    @deleteSecond = Friendlist.find_by_friend_id(params[:id])
    @deleteFirst.delete
    @deleteSecond.delete
    redirect_to user_url(current_user)
  end

  def block_friend
    @block = BlockList.new
    @block.user_id = current_user.id
    @temp = User.find(params[:id])
    @block.blocked_friend_id = @temp.id

    @block.save

    @block = BlockList.new

    @temp = User.find(params[:id])
    @block.user_id = @temp.id
    @block.blocked_friend_id = current_user.id
    @block.blocked_status = true

    @block.save

    self.remove_friend
  end

  def un_block_friend
    BlockList.find_by_blocked_friend_id(params[:id]).delete
    BlockList.find_by_user_id(params[:id]).delete
    redirect_to user_url(current_user)
  end

  def edit_privacy
    @privacy = ProfilePrivacy.find_by(user_id: params[:id])
  end
  
  def update_privacy
    respond_to do |format|
      if @privacy.update(privacy_params)
        format.html { redirect_to user_url(@privacy.user), notice: "Privacy updated." }
        format.json { render :show, status: :ok, location: @privacy.user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @privacy.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_privacy
      @privacy = ProfilePrivacy.find_by(user_id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def privacy_params
      params.require(:profile_privacy).permit(:email, :phone_number, :profile_photo, :friends, :groups)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div class="container-xs">
  <div class="row">
    <div class="col-md-3">
      <%= image_tag user.profile_picture , size: "200x200" ,class:"rounded-circle"%>
      <% iscurrent = false %>
      <% if current_user == user %>
        <% iscurrent = true %>
      <% end %>
      <% isfriend = false %>
      <% unless iscurrent %>
        <% if current_user.friends.include?(user) %>
          <% isfriend = true %>
        <% end %>
      <% end %>
      <h1><%= user.user_name %></h1>
      <% if iscurrent or @privacy.phone_number=="public" or (@privacy.phone_number=="friends" and isfriend) %>
        <h5>Phone Number : <%= user.phone_number%></h5>
      <% end %>
      <% if iscurrent or @privacy.email=="public" or (@privacy.email=="friends" and isfriend) %>
        <h5>Email : <%= user.email%></h5>
      <% end %>
      <% if @user == current_user%>
        <%=link_to 'Edit Profile',edit_user_registration_url,class:"btn btn-primary ml-3"%>
        <%=link_to 'Edit Privacy',edit_privacy_url(current_user),class:"btn btn-primary ml-3"%>
      <%end%>
    </div>
    <div class="col-md-6">
      <%= render "posts/form", post: posts_url %>
      <h1>Posts</h1>
      <div class="card mt-2 p-0">
        <div class="card-header bg-white border-bottom-0">
          <% @posts=Post.where(user_id: user.id) %>
          <% @posts.each do |post| %>
            <%= render 'posts/post', post: post %>
            <p>
            </p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <% if iscurrent or @privacy.friends=="public" or (@privacy.friends=="friends" and isfriend) %>
        <h3><%= button_to 'Friends', friends_path(user) %></h3>
      <%end%>
      <% if iscurrent or @privacy.groups=="public" or (@privacy.groups=="friends" and isfriend) %>
        <h3><%= button_to 'Groups', user_groups_path(user) %></h3>
      <%end%>
    </div>
  </div>
</div>

app/views/users/edit_privacy.html.erb
<%= form_with model: @privacy do |form| %>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.select :email, ["public", "friends", "only_me"] %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.select :phone_number, ["public", "friends", "only_me"] %>
  </div>

  <div>
    <%= form.label :profile_photo, style: "display: block" %>
    <%= form.select :profile_photo, ["public", "friends", "only_me"] %>
  </div>

  <div>
    <%= form.label :friends, style: "display: block" %>
    <%= form.select :friends, ["public", "friends", "only_me"] %>
  </div>

  <div>
    <%= form.label :groups, style: "display: block" %>
    <%= form.select :groups, ["public", "friends", "only_me"] %>
  </div> <br>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/friends.html.erb
<div class="container-xs">
  <div class="row">
    <div class="col-4">      
      <h1>Friends</h1>
      <table>
            <% @user.friendlists.each do |friend| %>
            <tbody>
                  <tr>
                        <% if friend.status == true %>
                              <% temp = User.find(friend.friend_id)%>
                              <td><%= image_tag temp.profile_picture,class:"rounded-circle",style:"max-width:50px;"%></td>
                              <td><strong><a href="<%= user_url(temp)%>"><%=temp.user_name%></a></strong></td>
                              <%if @user == current_user%>
                              <td> <%= button_to 'Remove Friend', remove_friend_path(current_user.id), method: :delete %> </td>
                              <td> <%= button_to 'Block Friend', block_friend_path(friend.friend_id)%> </td>
                              <%end%>
                        <%end%>
                  </tr>
            </tbody>
            <%end%>
      </table>
    </div>

    <%if @user == current_user%>
    <div class="col">
      <h2>Pending Requests</h2>
      <table>
            <% @user.friendlists.each do |friend| %>
            <tbody>
                  <tr>
                        <% if friend.status == false %>
                              <% temp = User.find(friend.friend_id)%>
                              <td> <%= temp.user_name%> </td>
                        <%end%>
                  </tr>
            </tbody>
            <%end%>
      </table>
    </div>
    <div class="col">
      <h2>Received Requests</h2>
      <table>
            
            <tbody>
                  
                  <%temp = @user.requests_received%>
                  <% temp.map { |user| %>
                  <tr>
                        <td> <%= user.user_name %>   </td>
                        <td> <%= button_to 'Accept Friend Request', accept_friend_request_path(current_user.id) %> </td>
                        <td> <%= button_to 'Remove Friend Request', remove_friend_request_path(current_user.id), method: :delete %> </td>
                  </tr>
                  <% }.join("\n ") %>
            </tbody>
      </table>
    </div>
    <div class="col">
      <h2>Blocked</h2>
      <table>
            <% @user.block_lists.each do |friend| %>
            <tbody>
                  <tr>
                        <%if friend.blocked_status == false%>
                              <% temp = User.find(friend.blocked_friend_id)%>
                              <td> <%= temp.user_name%> </td>
                              <td> <%= button_to 'Un Block', un_block_friend_path(friend.blocked_friend_id), method: :delete %> </td>
                        <%end%>
                  </tr>
            </tbody>
            <%end%>
      </table>
      <br>
    </div>
    <%end%>
  </div>
</div>

app/views/users/groups.html.erb
<h1>Joined Groups</h1>
<% current_user.groups.each do |group| %>
      <%= render 'groups/group', group: group %>
      <%= button_to 'Leave', remove_user_from_group_path(group.id), method: :delete%>
<% end %>

app/views/users/index.html.erb
<h1><%= t("Find New Friends") %>! :D</h1>

<% @users.each do |user| %>
    
    
      <div class="card">
        <%= image_tag user.profile_picture , size: "200x200" %>
        <div class="card-body">

        <p>
          <strong style="color : Red" class="card-title" ><%= t("Name")%>:</strong>
          <%= user.user_name %>
        </p>

        <br>
          <%= link_to t('Show Profile') ,show_user_path(id: user.id)%>
          <%= button_to t('Send Friend Request'), send_friend_request_path(user.id) %>
        <br>
        </div>

        
      </div>
<% end %>

app/views/users/show.html.erb
<h1>  <%= @user.user_name%>'s Profile </h1>

<%= render @user %>