config/routes.rb
Rails.application.routes.draw do
  #                 USERS ROUTES

  get 'users/index'
  devise_for :users, controllers: {  sessions: 'users/sessions'  }
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  resources :users, :only =>[:show]
  get 'users/:id', to: 'users#show', as: 'show_user'
 
  # Friends routes

  match '/users',   to: 'users#index',   via: 'get'
  post 'users/send_friend_request/:id', to: 'users#send_friend_request', as: 'send_friend_request'
  delete 'users/remove_friend_request/:id', to: 'users#remove_friend_request', as: 'remove_friend_request'
  delete 'users/remove_friend/:id', to: 'users#remove_friend', as: 'remove_friend'
  post 'users/block_friend/:id', to: 'users#block_friend', as: 'block_friend'
  delete 'users/un_block_friend/:id', to: 'users#un_block_friend', as: 'un_block_friend'
  post 'users/accept_friend_request/:id', to: 'users#accept_friend_request', as: 'accept_friend_request'

  # Profile
  scope 'users' do
    post '/friends/:profile_id', to: 'users#friends', as: 'friends'
    post '/groups/:profile_id', to: 'users#groups', as: 'user_groups'
    get 'privacy/:id', to: 'users#edit_privacy', as: 'edit_privacy'
    patch 'privacy/:id', to: 'users#update_privacy', as: 'profile_privacy'
  end

  # Events routes

  resources :events do  
    post 'going', to: 'events#save_going', as: 'going'
    post 'interested', to: 'events#save_interested', as: 'interested'
    delete 'delete_invitation', to: 'events#delete_invitation', as: 'delete_invitation'
    delete 'delete_response', to: 'events#delete_response', as: 'delete_response'
  end

  get "comments/index"
  resources :posts do
    resources :comments
  end
  # Post Reactions routes
  #Like
  post "posts/:id/likes", to: "likes#create", as: "add_likes"
  delete "posts/:id/likes/:id", to: "likes#destroy", as: "remove_likes"
  #Angry
  post "posts/:id/angry", to: "angries#create", as: "add_angry"
  delete "posts/:id/angry/:id", to: "angries#destroy", as: "remove_angry"
  #Heart
  resources :hearts, only: [:create, :destroy]
  post "posts/:id/hearts", to: "hearts#create", as: "add_hearts"
  delete "posts/:id/hearts/:id", to: "hearts#destroy", as: "remove_hearts"
  #Sad
  post "posts/:id/sads", to: "sads#create", as: "add_sads"
  delete "posts/:id/sads/:id", to: "sads#destroy", as: "remove_sads"
  #Wow
  post "posts/:id/wows", to: "wows#create", as: "add_wows"
  delete "posts/:id/wows/:id", to: "wows#destroy", as: "remove_wows"
  # Comment Delete and Update Routes
  delete "posts/:id/comment/:id", to: "comments#destroy_comment", as: "destroy_comment"
  put "posts/:id/comments/:id", to: "comments#update_comment", as: "update_comment"


  #                    GROUPS ROUTES
  

  get 'groups', to: 'groups#index' ,as: 'groups'
  post 'groups/index', to: 'groups#create',as: 'groups_create'
  get 'groups/new', to: 'groups#new'
  post 'groups/join_group/:id', to: 'groups#join_group' , as: 'join_group'
  delete 'groups/remove_user_from_group/:id', to: 'groups#remove_user_from_group' , as: 'remove_user_from_group'
  delete 'groups/delete/:id', to: 'groups#delete' , as: 'delete'

  # Notifications

  get 'notifications/:user_id', to: 'notifications#index', as:'show_notifications'

  # Not found
  get 'not_found', to: 'pages#not_found', as:'not_found'

  root to: "home#index", as:"home"

  # locale
  get '*path?locale=:locale', to: 'application#switch_locale', as: 'switch'

  # will cause storage photos not to render
  #get "*path", to: redirect('not_found')
  

end

app/models/event.rb
class Event < ApplicationRecord
    has_and_belongs_to_many :invited, class_name: 'User'

    belongs_to :user
    
    has_many :event_interests, dependent: :destroy
    has_many :interested, through: :event_interests, source: :user

    has_many :event_going_users, dependent: :destroy
    has_many :going, through: :event_going_users, source: :user

    validates :privacy, inclusion: { in: %w(public friends friends_except only_me), message: "%{value} is not valid" }
    validates :name, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /events or /events.json
  def index
    events = current_user.events
    current_user.friends.each { |friend| events.concat(friend.events.where.not(privacy: "only_me")) }
    @events = events.sort_by { |event| -event.created_at.to_i }
  end

  # GET /events/1 or /events/1.json
  def show
    @going = []
    @interested = []
    current_user.friends.each{
      |friend| 
      if friend.going_to_events.include?(@event)
        
        @going.append(friend)
      end
      if friend.interested_to_events.include?(@event)
        @interested.append(friend)
      end
    }
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user

    respond_to do |format|
      if @event.save
        message = "#{current_user.user_name} added new event #{@event.name}"
        scope = @event.privacy == "only_me" ? [] : current_user.friends
        SendNotificationsJob.perform_now({:message => message, :scope => scope})
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # POST /going
  def save_going
    @event = Event.find(params[:event_id])
    @event.going.append(current_user)
    if @event.interested.include?(current_user)
      @event.interested.delete(current_user)
    end
    redirect_to event_url(@event)
  end

  # POST /interested
  def save_interested
    @event = Event.find(params[:event_id])
    @event.interested.append(current_user)
    if @event.going.include?(current_user)
      @event.going.delete(current_user)
    end
    redirect_to event_url(@event)
  end
  
  # DELETE /events/1/delete_invitation
  def delete_invitation
  # Delete invitation on responding
  end

  # DELETE /events/1/delete_response
  def delete_response
    @event = Event.find(params[:event_id])
    if @event.going.include?(current_user)
      @event.going.delete(current_user)
    else
      @event.interested.delete(current_user)
    end
    redirect_to event_url(@event)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :description, :online_InPerson, :post_permission, :invite_permission, :location, :privacy, status)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">

  <div class="card mt-2 p-0">
      <div class="card-header bg-white border-bottom-0">
        <div class="row">
          <strong><%= event.name %> - <%= event.date.to_s(:long) %></strong><br>
          <div class="card-body">
            <p>  
              <%= event.description %>
            </p>
            <p>
            <% if event.online_InPerson %>
              Online
            <% else %>
              In Person
            <% end %>
            </p>
            <p>
              <%= event.location %>
            </p>

            <p>
              <strong>Going</strong>
              <%= event.going.count%>
              <% @going.each do |friend| %>
                <div>
                  <%= friend.user_name %>
              </div>
              <%end%>
            </p>
            <p>
              <strong>Interested</strong>
              <%= event.interested.count%>
              <% @interested.each do |friend| %>
                <div>
                  <%= friend.user_name %>
                </div>
              <%end%>
            </p>
            <P>
            <%if current_user.id == event.user_id%>
            <strong>Privacy:</strong>
            <%=event.privacy%>
            <%end%>
            </p>
          </div>
        </div>
      </div>
  </div>
  
  <% unless @event == nil %>
    <% status = nil %>
    <% if @event.going.include?(current_user)%>
      <% status = "Going" %>
    <% elsif @event.interested.include?(current_user) %>
      <% status = "Interested" %>
    <%end%>
    <strong><%= status %></strong>
    <% unless status == "Going" %>
      <%= button_to "Going", event_going_path(event_id: @event.id), method: :post %>
    <%end%>
    <% puts @status %>
    <% unless status == "Interested" %>
      <%= button_to "Interested", event_interested_path(event_id: @event.id), method: :post %>
    <%end%>
    <% unless status == nil %>
      <%if current_user.invited_to_events.include?(@event) %>
        <%= button_to "Not going", event_delete_invitation, method: :delete %>
      <%else%>
        <%= button_to "Not going", event_delete_response_path(event_id: @event.id), method: :delete %>
      <%end%>
    <%end%>
  <%end%>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date, step: 'any' %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :online_InPerson, style: "display: block" %>
    <%= form.check_box :online_InPerson %>
  </div>

  <div>
    <%= form.label :privacy, style: "display: block" %>
    <%= form.select :privacy, ["public", "friends", "only_me"] %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= t("Editing event") %></h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to t("Show this event"), @event %> |
  <%= link_to t("Back to events"), events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t"Events" %></h1>

<div id="events">
  <%@going=[]%>
  <%@interested=[]%>
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to t("Show this event"), event %>
    </p>
  <% end %>
</div>

<%= link_to t("New event"), new_event_path %>

app/views/events/new.html.erb
<h1>t("New event")</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to t("Back to events"), events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <%= link_to t("Edit this event"), edit_event_path(@event) %> |
  <%= link_to t("Back to events"), events_path %>

  <%= button_to t("Destroy this event"), @event, method: :delete %>
</div>