config/routes.rb
Rails.application.routes.draw do
  #                 USERS ROUTES

  get 'users/index'
  devise_for :users, controllers: {  sessions: 'users/sessions'  }
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  resources :users, :only =>[:show]
  get 'users/:id', to: 'users#show', as: 'show_user'
 
  # Friends routes

  match '/users',   to: 'users#index',   via: 'get'
  post 'users/send_friend_request/:id', to: 'users#send_friend_request', as: 'send_friend_request'
  delete 'users/remove_friend_request/:id', to: 'users#remove_friend_request', as: 'remove_friend_request'
  delete 'users/remove_friend/:id', to: 'users#remove_friend', as: 'remove_friend'
  post 'users/block_friend/:id', to: 'users#block_friend', as: 'block_friend'
  delete 'users/un_block_friend/:id', to: 'users#un_block_friend', as: 'un_block_friend'
  post 'users/accept_friend_request/:id', to: 'users#accept_friend_request', as: 'accept_friend_request'

  # Profile
  scope 'users' do
    post '/friends/:profile_id', to: 'users#friends', as: 'friends'
    post '/groups/:profile_id', to: 'users#groups', as: 'user_groups'
    get 'privacy/:id', to: 'users#edit_privacy', as: 'edit_privacy'
    patch 'privacy/:id', to: 'users#update_privacy', as: 'profile_privacy'
  end

  # Events routes

  resources :events do  
    post 'going', to: 'events#save_going', as: 'going'
    post 'interested', to: 'events#save_interested', as: 'interested'
    delete 'delete_invitation', to: 'events#delete_invitation', as: 'delete_invitation'
    delete 'delete_response', to: 'events#delete_response', as: 'delete_response'
  end

  get "comments/index"
  resources :posts do
    resources :comments
  end
  # Post Reactions routes
  #Like
  post "posts/:id/likes", to: "likes#create", as: "add_likes"
  delete "posts/:id/likes/:id", to: "likes#destroy", as: "remove_likes"
  #Angry
  post "posts/:id/angry", to: "angries#create", as: "add_angry"
  delete "posts/:id/angry/:id", to: "angries#destroy", as: "remove_angry"
  #Heart
  resources :hearts, only: [:create, :destroy]
  post "posts/:id/hearts", to: "hearts#create", as: "add_hearts"
  delete "posts/:id/hearts/:id", to: "hearts#destroy", as: "remove_hearts"
  #Sad
  post "posts/:id/sads", to: "sads#create", as: "add_sads"
  delete "posts/:id/sads/:id", to: "sads#destroy", as: "remove_sads"
  #Wow
  post "posts/:id/wows", to: "wows#create", as: "add_wows"
  delete "posts/:id/wows/:id", to: "wows#destroy", as: "remove_wows"
  # Comment Delete and Update Routes
  delete "posts/:id/comment/:id", to: "comments#destroy_comment", as: "destroy_comment"
  put "posts/:id/comments/:id", to: "comments#update_comment", as: "update_comment"


  #                    GROUPS ROUTES
  

  get 'groups', to: 'groups#index' ,as: 'groups'
  post 'groups/index', to: 'groups#create',as: 'groups_create'
  get 'groups/new', to: 'groups#new'
  post 'groups/join_group/:id', to: 'groups#join_group' , as: 'join_group'
  delete 'groups/remove_user_from_group/:id', to: 'groups#remove_user_from_group' , as: 'remove_user_from_group'
  delete 'groups/delete/:id', to: 'groups#delete' , as: 'delete'

  # Notifications

  get 'notifications/:user_id', to: 'notifications#index', as:'show_notifications'

  # Not found
  get 'not_found', to: 'pages#not_found', as:'not_found'

  root to: "home#index", as:"home"

  # locale
  get '*path?locale=:locale', to: 'application#switch_locale', as: 'switch'

  # will cause storage photos not to render
  #get "*path", to: redirect('not_found')
  

end

app/models/post.rb
class PostCreationValidation < ActiveModel::Validator
  def validate(record)
    if record.text.length < 1  &&  record.image.attached? == false
      record.errors.add :base, "Post must contain text is or an Image to be posted "
    end
  end
end


class Post < ApplicationRecord
  has_many_attached :image
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :angries, dependent: :destroy
  has_many :hearts, dependent: :destroy
  has_many :sads, dependent: :destroy
  has_many :wows, dependent: :destroy
  belongs_to :user
  #validates_with PostCreationValidation
  #validates :text, presence: true
  #validates :image, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :create, :index]
  before_action :correct_user?, only: [:edit, :update, :destroy]

  @user = User.all
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @comment = Comment.new(post_id: params[:post_id])
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new()
    @post.text = params[:text]
    @post.image = params[:image]
    @post.save
    respond_to do |format|
      if @post.save
        message = "#{current_user.user_name} added a new post"
        scope = current_user.friends
        SendNotificationsJob.perform_now({:message => message, :scope => scope})
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
  end

  def correct_user?
    @post = Post.find_by(id: params[:id])

    redirect_to post_url(@post), notice: "Cannot edit or delete others post" unless @post.user == current_user
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:text, :user_id, :comment, image: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with url: posts_url,method: :post do |form| %>
  <div class="form-group">
    <div>
      <%= form.text_area :text,placeholder:"Say something inspiring to your Fake Friends",class:"form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col">

        <%= form.file_field :image, multiple:true ,class:"form-control"%>
      </div>

      <div class="col">
        <%= form.submit 'Post' ,class:"form-control text-white" ,style:"background-color:#4267B2;"%>
      </div>
    
  </div>
<% end %>

app/views/posts/_post.html.erb
<%if signed_in?%>
  <% like = current_user.likes.find_by(post: post) %>
  <% heart = current_user.hearts.find_by(post: post) %>
  <% angry = current_user.angries.find_by(post: post) %>
  <% sad = current_user.sads.find_by(post: post) %>
  <% wow = current_user.wows.find_by(post: post) %>
<%end%>

  <div class="card mt-2 p-0">
    <div class="card-header bg-white border-bottom-0">
      <div class="row">
        <div class="col-10">
          <%= image_tag post.user.profile_picture,class:"rounded-circle mr-2",style:"max-width:8%;"%>
          <strong class="ml-2"style="color:#4267B2;"><a href="<%= user_url(post.user)%>"><%=post.user.user_name%></a></strong>
        </div>
        <div class="col-1 p-0 m-0">
          <% if current_user == post.user%>
            <%= link_to post_path(post), method: :delete   do %>
              <%=image_tag 'trash.svg',style:"max-width:17px;",style:"max-width:17px;",class:"p-0 "%>
            <%end%>
          </div>
          <div class="col-1 m-0 p-0">
            <%= link_to  edit_post_path(post)  do %>
              <%=image_tag 'edit.svg',style:"max-width:17px;",style:"max-width:17px;",class:"p-0 "%>
            <%end%>
          <%end%>
        </div>
      </div>
    </div>
    <div class="card-body">
      <p class="card-text">  <%= post.text %></p>
      <% post.image.each do |i| %>
        <%= image_tag(i,class:"w-100 m-0 p-0") %>
      <% end %>
      <div class="card-header mb-2">
        <%= react = post.likes.count + post.hearts.count + post.angries.count + post.sads.count + post.wows.count %> <%=image_tag 'like.svg',style:"max-width:17px;",style:"max-width:17px;"%>
      </div>
      <div class="col">
        <% if like.nil? %>
          <%= link_to  add_likes_url(post), method: :post do%>
            <%= image_tag 'like1.svg',style:"max-width:17px;"%>
          <%end%>
        <% else %>
          <%= link_to  remove_likes_url(like), method: :delete do%>
            <%= image_tag 'like1.svg',style:"max-width:17px;"%>
          <%end%>
        <% end %>
     
        <% if heart.nil? %>
          <%= link_to(  add_hearts_url(post),method: :post) do%>
            <%= image_tag 'hearts.svg',style:"max-width:17px;"%>
          <%end%>
        <% else %>
          <%= link_to  remove_hearts_url(heart), method: :delete do%>
            <%= image_tag 'hearts.svg',style:"max-width:17px;"%>
          <%end%>
        <% end %>
      
        <% if angry.nil? %>
          <%= link_to  add_angry_url(post),method: :post do%>
            <%= image_tag 'angry.svg',style:"max-width:17px;"%>
          <%end%>
        <% else %>
          <%= link_to  remove_angry_url(angry), method: :delete do%>
            <%= image_tag 'angry.svg',style:"max-width:17px;"%>
          <%end%>
        <% end %>
     
        <% if sad.nil? %>
          <%= link_to  add_sads_url(post),method: :post do%>
            <%= image_tag 'sad.svg',style:"max-width:17px;"%>
          <%end%>
        <% else %>
          <%= link_to  remove_sads_url(sad), method: :delete do%>
            <%= image_tag 'sad.svg',style:"max-width:17px;"%>
          <%end%>
        <% end %>
      
        <% if wow.nil? %>
          <%= link_to  add_wows_url(post),method: :post do%>
            <%= image_tag 'as.svg',style:"max-width:17px;"%>
          <%end%>
        <% else %>
          <%= link_to  remove_wows_url(wow), method: :delete do%>
            <%= image_tag 'as.svg',style:"max-width:17px;"%>
          <%end%>
        <% end %>
      </div>
        <%= render 'comments/form' ,post:post%>
        <% if post.comments%>
      <%= render post.comments %>

        <%else%>
        <%end%>
    </div>
  </div>
  

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to t("Show this post"), @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t"Posts" %></h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to t("Show this post"), post %>
    </p>
  <% end %>
</div>

<%= link_to t("New post"), new_post_path %>

app/views/posts/new.html.erb
<h1><%= link_to t("New post"), new_post_url %></h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to t("Back to posts"), posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<% @post.image.each do |i| %>
 <%= image_tag(i, size: "200x200") %>
<% end %>


<%= render @post %>